<?php

namespace Database\Seeders;

use App\Enums\MovieGenres;
use App\Models\Movie;
use Illuminate\Database\Seeder;

class MovieSeeder extends Seeder
{
    public function run(): void
    {
        $movies = [
            [
                'title' => 'The Dark Knight',
                'description' => 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
                'duration' => 152,
                'release_date' => '2008-07-18',
                'poster_url' => 'https://i1.sndcdn.com/artworks-000480914043-0a2fis-t500x500.jpg',
                'director' => 'Christopher Nolan',
                'genre' => [MovieGenres::Action, MovieGenres::Crime, MovieGenres::Drama],
                'rating' => 9.0,
                'language' => 'English',
                'country' => 'United States',
            ],
            [
                'title' => 'Inception',
                'description' => 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
                'duration' => 148,
                'release_date' => '2010-07-16',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
                'director' => 'Christopher Nolan',
                'genre' => [MovieGenres::Action, MovieGenres::SciFi, MovieGenres::Thriller],
                'rating' => 8.8,
                'language' => 'English',
                'country' => 'United States',
            ],
            [
                'title' => 'The Shawshank Redemption',
                'description' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
                'duration' => 142,
                'release_date' => '1994-09-23',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
                'director' => 'Frank Darabont',
                'genre' => [MovieGenres::Drama],
                'rating' => 9.3,
                'language' => 'English',
                'country' => 'United States',
            ],
            [
                'title' => 'The Godfather',
                'description' => 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
                'duration' => 175,
                'release_date' => '1972-03-14',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
                'director' => 'Francis Ford Coppola',
                'genre' => [MovieGenres::Crime, MovieGenres::Drama],
                'rating' => 9.2,
                'language' => 'English',
                'country' => 'United States',
            ],
            [
                'title' => 'Pulp Fiction',
                'description' => 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
                'duration' => 154,
                'release_date' => '1994-09-10',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
                'director' => 'Quentin Tarantino',
                'genre' => [MovieGenres::Crime, MovieGenres::Drama],
                'rating' => 8.9,
                'language' => 'English',
                'country' => 'United States',
            ],
            [
                'title' => 'Parasite',
                'description' => 'All unemployed, Ki-taek and his family take peculiar interest in the wealthy and glamorous Parks, as they ingratiate themselves into their lives and get entangled in an unexpected incident.',
                'duration' => 132,
                'release_date' => '2019-05-30',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
                'director' => 'Bong Joon-ho',
                'genre' => [MovieGenres::Drama, MovieGenres::Thriller],
                'rating' => 8.6,
                'language' => 'Korean',
                'country' => 'South Korea',
            ],
            [
                'title' => 'Spirited Away',
                'description' => 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
                'duration' => 125,
                'release_date' => '2001-07-20',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
                'director' => 'Hayao Miyazaki',
                'genre' => [MovieGenres::Animation, MovieGenres::Adventure, MovieGenres::Fantasy],
                'rating' => 8.6,
                'language' => 'Japanese',
                'country' => 'Japan',
            ],
            [
                'title' => 'The Matrix',
                'description' => 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
                'duration' => 136,
                'release_date' => '1999-03-31',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
                'director' => 'Lana Wachowski',
                'genre' => [MovieGenres::Action, MovieGenres::SciFi],
                'rating' => 8.7,
                'language' => 'English',
                'country' => 'United States',
            ],
            [
                'title' => 'The Silence of the Lambs',
                'description' => 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
                'duration' => 118,
                'release_date' => '1991-02-01',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg',
                'director' => 'Jonathan Demme',
                'genre' => [MovieGenres::Crime, MovieGenres::Drama, MovieGenres::Thriller],
                'rating' => 8.6,
                'language' => 'English',
                'country' => 'United States',
            ],
            [
                'title' => 'The Lion King',
                'description' => 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
                'duration' => 88,
                'release_date' => '1994-06-24',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
                'director' => 'Roger Allers',
                'genre' => [MovieGenres::Animation, MovieGenres::Adventure, MovieGenres::Drama],
                'rating' => 8.5,
                'language' => 'English',
                'country' => 'United States',
            ],
            [
                'title' => 'Interstellar',
                'description' => 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
                'duration' => 169,
                'release_date' => '2014-11-07',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
                'director' => 'Christopher Nolan',
                'genre' => [MovieGenres::Adventure, MovieGenres::Drama, MovieGenres::SciFi],
                'rating' => 8.6,
                'language' => 'English',
                'country' => 'United States',
            ],
            [
                'title' => 'Your Name',
                'description' => 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
                'duration' => 106,
                'release_date' => '2016-08-26',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg',
                'director' => 'Makoto Shinkai',
                'genre' => [MovieGenres::Animation, MovieGenres::Drama, MovieGenres::Fantasy],
                'rating' => 8.4,
                'language' => 'Japanese',
                'country' => 'Japan',
            ],
            [
                'title' => 'The Green Mile',
                'description' => 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
                'duration' => 189,
                'release_date' => '1999-12-10',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg',
                'director' => 'Frank Darabont',
                'genre' => [MovieGenres::Crime, MovieGenres::Drama, MovieGenres::Fantasy],
                'rating' => 8.6,
                'language' => 'English',
                'country' => 'United States',
            ],

            [
                'title' => 'The Apartment',
                'description' => 'A man tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue.',
                'duration' => 125,
                'release_date' => '1960-06-15',
                'poster_url' => 'https://image.tmdb.org/t/p/w500/5K7cOHoay2mZusSLezBOY0Qxh8a.jpg',
                'director' => 'Billy Wilder',
                'genre' => [MovieGenres::Comedy, MovieGenres::Drama, MovieGenres::Romance],
                'rating' => 8.3,
                'language' => 'English',
                'country' => 'United States',
            ],
        ];

        foreach ($movies as $movie) {
            Movie::firstOrCreate(
                ['title' => $movie['title']],
                [
                    'title' => $movie['title'],
                    'description' => $movie['description'],
                    'duration' => $movie['duration'],
                    'release_date' => $movie['release_date'],
                    'poster_url' => $movie['poster_url'],
                    'director' => $movie['director'],
                    'genre' => $movie['genre'],
                    'rating' => $movie['rating'],
                    'language' => $movie['language'],
                    'country' => $movie['country'],
                ]
            );
        }

        $this->command->info('Successfully seeded sample movies');
    }
}
